### ISSUE TITLE
grafana 模版变量定义不生效

### ISSUE THREAD

**Issue by haoyuxy** [masato25/grafana-openfalcon#6]
我用falcon grafana的时候定义一个模版变量， port
thread#active#count/jmxport=[[port]]
在使用的时候发现port替换到falcon的表达式为jmxport={21071,21097}')，拿不到数据
我替换成 jmxport=(21906|21083)') 这个后能正常
大神能帮忙看看么
多谢~

**Comment by masato25** [comment]
基本上你的使用方式是對的.
這邊的查詢會映射到後端轉換成查詢指標的regex sql查詢.
如果你想要支援 "," 換行那我會建議你修改後端對應的api
將 "," replace 為 "|"

**Comment by haoyuxy** [comment]
嗯，好的，多谢啦。

**Comment by haoyuxy** [comment]
已经改好了，谢啦
