### ISSUE TITLE
主机名包含dot时取不到数据

### ISSUE THREAD

**Issue by ghost** [masato25/grafana-openfalcon#7]
当主机名包含小数点时，小数点和其后一个字符在发送post请求时会变为 undefined

**Comment by masato25** [comment]
@xcFelix 可否提供發生錯誤的範例？ 方便排查使用.
另外建議主機名可以的話不要帶有小數點.
如果是ip的話就沒有這個限制. 這個plugin 有針對ip做特殊處裡

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/22268535/29500746-0a9fd196-8656-11e7-9e60-907fc85e17b5.png)

**Comment by masato25** [comment]
這邊有一個根本性的問題在是plugin的前端使用行為問題. (它只有一行的輸入框, 所以它需要依據某些特定的符號去判別它要找尋的是endpoint 還是 metric)
所以"." 在這邊具有其特殊意義, (目前只有支援ip 型態的host name可以跳脫)
當初實做的定義中,是不建議hostname帶有 "." 的形式存在. 如果要支援這個作法, 需要從根本面的改寫現在的plugin的所有行為 & 前端ui.

如果你還是希望支援"." 的轉換, 你可從後端api 將 "undefined"  -轉換->  "."
或是你可以參考
https://github.com/masato25/grafana-openfalcon-datasource/blob/master/query_ctrl.js#L51
這邊的還原作法,撰寫專屬於你們內部使用的hostname 的轉換代碼.
